version: '3.8'

services:
  deepseek-ocr:
    image: nvidia/cuda:11.8.0-runtime-ubuntu22.04
    container_name: deepseek-ocr-benchmark
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - HF_HOME=/workspace/huggingface_cache
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/workspace
      - huggingface_cache:/workspace/huggingface_cache
      - benchmark_output:/workspace/benchmark_output
    working_dir: /workspace
    command: >
      bash -c "
        apt-get update && apt-get install -y python3 python3-pip git &&
        pip3 install --upgrade pip &&
        pip3 install -r requirements.txt &&
        pip3 install vllm==0.8.5 torch torchvision &&
        python3 benchmark.py
      "
    shm_size: '24gb'

volumes:
  huggingface_cache:
    driver: local
  benchmark_output:
    driver: local
